#ifndef __MAIN_FUNC_FLAGS__
#define __MAIN_FUNC_FLAGS__

enum MainFunctionFlags {
        AL_INIT_ERROR = 1,
        AL_KEYBOARD_INSTALL_ERROR,
        AL_INIT_FONT_ADDONS_ERROR,
        AL_INIT_IMAGE_ADDON_ERROR,
        AL_LOAD_GAME_ICON_ERROR,
        AL_CREATE_DISPLAY_ERROR,
        AL_LOAD_FONT_ERROR,
        AL_LOAD_SAMPLE_ERROR,
        AL_SET_AUDIO_ERROR,
        AL_PLAY_SAMPLE_ERROR,
        AL_CREATE_EVENT_QUEUE_ERROR,
        AL_CREATE_TIMER_ERROR
};

#endif // __MAIN_FUNC_FLAGS__